server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: admin-route
          uri: http://localhost:8081
          predicates:
            - Path=/admin/**
        - id: app-route
          uri: http://localhost:8082
          predicates:
            - Path=/app/**
