server:
  port: 8082

spring:
  application:
    name: app
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ty_app?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

ty:
  organ-name: app-organ-name
  auth:
    token-ttl-seconds: 604800
